날씨 API 연결, 상세화면 작성
GangwonHyuIl/GangwonHyuIl pull request #38
Opened 2024-09-05 09:33 UTC by kimnahee1529

## Related Issue
- Issue #24
- Issue #18
- Issue #12
- Issue #20

## 작업 상세 내용
- 홈 화면에서 스피너 선택해 지역 변경 시 해당 지역에 맞는 날씨 정보 호출
  - 발표일자(base_date)는 당일날짜, 발표시각(base_time)은 현재 시각과 1일 8회의 정해진 Base_time과 가장 가까운 시간.
  - Response의 category는 POP, PTY를 사용
  "POP"(강수 확률), "PTY"(강수형태) - (단기) 없음(0), 비(1), 비/눈(2), 눈(3), 소나기(4) 
  날씨 아이콘은 강수형태에 따라 5개의 아이콘 사용
  - local.properties에 WEATHER_API_KEY 값 저장
 - 홈 화면에서 리스트 항목 선택 시 이동할 상세화면인 DetailActivity 화면 작성
 - 강수 확률 글자 색(rain_info) 추가

2024-09-05 14:04 UTC, sunjoolee requested changes

2024-09-05 14:04 UTC, sunjoolee commented on app/src/main/res/layout/activity_detail.xml
RecyclerView를 NestedScrollView로 감쌀 경우, RecyclerView의 모든 아이템들이 메모리에 올라가 성능 이점이 사라지게 됩니다!
RecyclerView 상단의 장소 상세 정보를 표시하는 레이아웃을 RecyclerView의 아이템으로 만들어서, 멀티뷰 타입을 이용하는 방식으로 구현하는 것이 좋을 것 같습니다!

2024-09-06 09:50 UTC, sunjoolee commented on app/build.gradle.kts
💯🥇

2024-09-06 10:40 UTC, sunjoolee requested changes

2024-09-06 10:40 UTC, sunjoolee commented on app/src/main/java/com/gangwonhyuil/gangwonhyuil/ui/home/detail/DetailItemAdapter.kt
> +        return when (viewType) {
뷰 타입과 inflate되는 ViewBinding 객체 매핑이 잘못된 것 같아요! 확인 부탁드립니다~

2024-09-06 10:40 UTC, sunjoolee commented on app/src/main/java/com/gangwonhyuil/gangwonhyuil/ui/home/office/PlaceItem.kt
> +    data class Place(
data class가 직접 Eigenvalue 인터페이스를 상속하는 것이 아니라, 
Eigenvalue를 상속하는 PlaceItem sealed interface를 상속하도록 구현한 이유 있나용?

2024-09-06 10:43 UTC, kimnahee1529 commented on app/src/main/java/com/gangwonhyuil/gangwonhyuil/ui/home/office/PlaceItem.kt
> +    data class Place(
네! 수정했습니다

2024-09-06 10:43 UTC, kimnahee1529 commented on app/src/main/java/com/gangwonhyuil/gangwonhyuil/ui/home/detail/DetailItemAdapter.kt
> +        return when (viewType) {
네! 수정했습니다

2024-09-06 10:58 UTC, kimnahee1529 commented on app/src/main/java/com/gangwonhyuil/gangwonhyuil/ui/home/office/PlaceItem.kt
> +    data class Place(
처음에 상세 화면에서 쓰는 data class까지 모아놓고 멀티뷰타입으로 구현하려고 PlaceItem sealed interface를 상속하게 했는데 지금은 상세 화면에서 쓰는 PlaceDetailItem sealed interface를 추가해서 필요가 없어진 것 같습니다. 

그냥 PlaceItem data class가 Eigenvalue 인터페이스를 상속하게 수정했습니다!

2024-09-06 11:06 UTC, sunjoolee approved these changes

2024-09-06 11:06 UTC, merged

2024-09-06 14:43 UTC, kimnahee1529 commented on app/src/main/res/layout/activity_detail.xml
네 멀티뷰 타입 구현하는 방식으로 수정했습니다!